# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  #adapter: jdbcmysql
  adapter: mysql2
  host: localhost
  database: smscow_dev
  username: root
  password: