get_latest_messages:
  every: "30m"
  queue: cron
  class: Cron::GetLatestMessagesJob
  description: "Get latest messages for all registered phones"
  rails_envs: development, production, staging

send_autoreplies:
  every: "30m"
  class: Cron::SendAutorepliesJob
  description: "Send auto-replies if necessary"
  rails_envs: development, production, staging